import React from 'react'
import MainContainer from '../components/MainContainer'
import type { Metadata } from 'next'
import AnimatedText from '../components/animate/AnimatedText'
import Image from 'next/image'
import AnimatedCounter from '../components/animate/AnimatedCounter'
export const metadata: Metadata = {
  title: 'About Me',
  description: 'Generated by create next app',
}
export default function About() {
  return (
    <MainContainer style='py-24 flex flex-col w-full gap-4'>
      <div className="flex flex-col justify-center">
        <AnimatedText text={`Coding is My Ninja Way`} style='!normal-case text-4xl lg:text-6xl text-center' />
        <div className="grid w-full grid-cols-8 gap-8 md:gap-16 md:py-8 pr-2 sm:pr-0">
          <div className="col-span-8 md:col-span-3 order-2 md:order-1 flex flex-col items-start justify-start">
            <p className='font-medium'>
              I'm a web & mobile developer from Karawang, West Java. I prefer to work as a front-end but it doesn't matter if I have to work back-end.
            </p>
            <p className='font-medium py-4'>
              I have about five years of experience in the world of programming, programming has become a hobby for me.
            </p>
            <p className="font-medium">
              I am always looking for new and innovative ways to bring my clients' visions to life. I look forward to the opportunity to bring my skills and passion to your next project.
            </p>
          </div>
          <div
            className='col-span-8 md:col-span-5 lg:col-span-3 order-1 md:order-2 relative h-max rounded-2xl border-2 border-solid border-dark bg-light p-8 dark:border-light dark:bg-dark'
          >
            <div className='absolute top-0 -right-3 -z-10 w-[102%] h-[103%] rounded-[2rem] rounded-br-3xl bg-dark dark:bg-light' />
            <Image src={'/img/about.jpg'} width={0} height={0} alt='about-img' className='w-full h-auto rounded-2xl' unoptimized />
          </div>
          <div
            className='col-span-8 flex-row items-center order-3 lg:order-3 lg:col-span-2 flex lg:flex-col lg:items-end justify-between'
          >
            <div className="flex flex-col lg:items-end justify-center items-center">
              <span className="inline-block md:text-7xl font-bold sm:text-6xl xs:text-5xl text-4xl">
                <AnimatedCounter value={20} />
                +
              </span>
              <h2 className="mb-4 text-base md:text-xl text-center lg:text-left font-medium capitalize text-dark/75 dark:text-light/75 ">
                satisfied clients
              </h2>
            </div>
            <div className="flex flex-col lg:items-end justify-center items-center">
              <span className="inline-block md:text-7xl font-bold sm:text-6xl xs:text-5xl text-4xl">
                <AnimatedCounter value={50} />
                +
              </span>
              <h2 className="mb-4 text-base md:text-xl text-center lg:text-left font-medium capitalize text-dark/75 dark:text-light/75 ">
                Projects Completed
              </h2>
            </div>
            <div className="flex flex-col lg:items-end justify-center items-center">
              <span className="inline-block md:text-7xl font-bold sm:text-6xl xs:text-5xl text-4xl">
                <AnimatedCounter value={5} />
                +
              </span>
              <h2 className="mb-4 text-base md:text-xl text-center lg:text-left font-medium capitalize text-dark/75 dark:text-light/75 ">
                Years Of Experience
              </h2>
            </div>
          </div>
        </div>
      </div>
    </MainContainer>
  )
}
