import React from 'react'
import type { Metadata } from 'next'
import MainContainer from '../components/MainContainer'
import AnimatedText from '../components/animate/AnimatedText'
import Image from 'next/image'
import { MySqlIcon, NextjsIcon, PhpIcon, ReactIcon, TailwindIcon } from '../components/svg'
import ProjectBox from '../components/ProjectBox'
import LaravelIcon from '../components/svg/LaravelIcon'
import BootstrapIcon from '../components/svg/BootstrapIcon'
export const metadata: Metadata = {
  title: 'My Project',
  description: 'Generated by create next app',
}
export default function Project() {
  return (
    <MainContainer style='py-24 flex flex-col w-full gap-4'>
      <div className="flex justify-center flex-col">
        <AnimatedText text={`Imagination Trumps Knowledge!`} style='text-4xl lg:text-8xl text-center' />
        <div className='flex flex-col py-8 gap-8 pr-2 md:pr-0'>
          <ProjectBox
            image='/img/projects/infolelang.png'
            title='Property Auction Website'
            desc='A website that presents information on the assets sold, both through auction and peace sale mechanisms. The assets informed on this website are assets that are secured by credit by the debtor to the Bank.'
          >
            <div className='md:px-2'>
              <ReactIcon height={24} width={24} className='fill-[#61DBFB] dark:fill-light' />
            </div>
            <div className='md:px-2'>
              <NextjsIcon height={24} width={24} className='fill-[#61DBFB] dark:fill-light' />
            </div>
            <div className='md:px-2'>
              <TailwindIcon height={24} width={24} className='fill-[#61DBFB] dark:fill-light' />
            </div>
          </ProjectBox>
          <ProjectBox
            image='/img/projects/klasterku.png'
            title='Web Application on Enterprise Cluster Submissions'
            desc='This application serves to submit a business grouping to the bank, so that the bank can record and group the business as well as record the credibility that exists on the business cluster.'
          >
            <div className='md:px-2'>
              <PhpIcon height={26} width={26} className='fill-[#474A8A] dark:fill-light' />
            </div>
            <div className='md:px-2'>
              <LaravelIcon height={26} width={26} className='fill-[#F05340] dark:fill-light' />
            </div>
            <div className='md:px-2'>
              <TailwindIcon height={24} width={24} className='fill-[#61DBFB] dark:fill-light' />
            </div>
            <div className='md:px-2'>
              <MySqlIcon height={24} width={24} className='fill-[#00758F] dark:fill-light' />
            </div>
          </ProjectBox>
          <ProjectBox
            image='/img/projects/tms.png'
            title='ERP Manufacturing System'
            desc={`An application that manages all the company needs, from production records to company records.`}
          >
            <div className='md:px-2'>
              <PhpIcon height={26} width={26} className='fill-[#474A8A] dark:fill-light' />
            </div>
            <div className='md:px-2'>
              <LaravelIcon height={26} width={26} className='fill-[#F05340] dark:fill-light' />
            </div>
            <div className='md:px-2'>
              <BootstrapIcon height={24} width={24} className='fill-[#602C50] dark:fill-light' />
            </div>
            <div className='md:px-2'>
              <MySqlIcon height={24} width={24} className='fill-[#00758F] dark:fill-light' />
            </div>
          </ProjectBox>
          <ProjectBox
            image='/img/projects/bensound.png'
            title='Company Profile & Tracking System'
            desc={`CMS Websites and applications to perform tracking of rented goods by customers. Customers can also check the rental date.`}
          >
            <div className='md:px-2'>
              <PhpIcon height={26} width={26} className='fill-[#474A8A] dark:fill-light' />
            </div>
            <div className='md:px-2'>
              <LaravelIcon height={26} width={26} className='fill-[#F05340] dark:fill-light' />
            </div>
            <div className='md:px-2'>
              <BootstrapIcon height={24} width={24} className='fill-[#602C50] dark:fill-light' />
            </div>
            <div className='md:px-2'>
              <MySqlIcon height={24} width={24} className='fill-[#00758F] dark:fill-light' />
            </div>
          </ProjectBox>
          <ProjectBox
            image='/img/projects/kets.png'
            title='Online Logistics System (Mobile App)'
            desc={`A driver search application to deliver goods and users can also sell or buy goods`}
          >
            <div className='md:px-2'>
              <ReactIcon height={24} width={24} className='fill-[#61DBFB] dark:fill-light' />
            </div>
            <div className='md:px-2'>
              <PhpIcon height={26} width={26} className='fill-[#474A8A] dark:fill-light' />
            </div>
            <div className='md:px-2'>
              <MySqlIcon height={24} width={24} className='fill-[#00758F] dark:fill-light' />
            </div>
          </ProjectBox>
          <ProjectBox
            image='/img/projects/sliovg.png'
            title='Online Video Generator & Email Blast Marketing'
            desc={`An application that can create videos according to templates such as birthday speeches and so on. Then the videos can be sent to corporate customers.`}
          >
            <div className='md:px-2'>
              <ReactIcon height={24} width={24} className='fill-[#61DBFB] dark:fill-light' />
            </div>
            <div className='md:px-2'>
              <PhpIcon height={26} width={26} className='fill-[#474A8A] dark:fill-light' />
            </div>
            <div className='md:px-2'>
              <MySqlIcon height={24} width={24} className='fill-[#00758F] dark:fill-light' />
            </div>
          </ProjectBox>
          <ProjectBox
            image='/img/projects/kembarjek.png'
            title='Online Transportation (Mobile App)'
            desc={`An online transportation application to make it easier for people to travel or engage in day-to-day activities. The mode of transportation can help in solving the problem of congestion.`}
          >
            <div className='md:px-2'>
              <ReactIcon height={24} width={24} className='fill-[#61DBFB] dark:fill-light' />
            </div>
            <div className='md:px-2'>
              <PhpIcon height={26} width={26} className='fill-[#474A8A] dark:fill-light' />
            </div>
            <div className='md:px-2'>
              <MySqlIcon height={24} width={24} className='fill-[#00758F] dark:fill-light' />
            </div>
          </ProjectBox>
        </div>
      </div>
    </MainContainer>
  )
}
