import React from 'react'
import type { Metadata } from 'next'
import MainContainer from '../components/MainContainer'
export const metadata: Metadata = {
  title: 'My Project',
  description: 'Generated by create next app',
}
export default function Project() {
  return (
    <MainContainer>Project</MainContainer>
  )
}
