import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import './globals.css'
import Navbar from './components/Navbar'
import { ThemesProvider } from './components/providers/ThemesProvider'

const montserrat = Montserrat({ subsets: ['latin'], variable: '--font-mont' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <meta name='viewport' content='width=device-width, initial-scale=1.0' />
      <body className={`${montserrat.variable} font-mont bg-light dark:bg-dark w-full min-h-screen`}>
        <ThemesProvider>
          <Navbar />
          {children}
        </ThemesProvider>
      </body>
    </html>
  )
}
